function string.split(str, sep)
    sep = sep or "%s"
    local t = {}

    for token in string.gmatch(str, "([^"..sep.."]+)") do
        table.insert(t, token)
    end

    return t
end

function string.trim(s)
   local from = s:match"^%s*()"
   return from > s:len() and "" or s:match(".*%S", from)
end

local function defineType(baseName, className, fieldList)
    local fields
    do
        local tmp = string.split(fieldList, ",")

        fields = {}

        for i,v in next,tmp,nil do
            fields[i] = string.trim(v)
        end
    end


    io.write("\tstatic class "..className.." extends "..baseName.." {\n")

    for i,field in next,fields,nil do
        io.write("\t\tfinal " .. field .. ";\n")
    end

    io.write"\n"

    -- Constructor
    io.write("\t\t"..className .. "(" .. fieldList .. ") {\n")

    for i,field in next,fields,nil do
        local name = string.split(field, "%s")[2]

        io.write("\t\t\tthis." .. name .. " = " .. name .. ";\n")
    end

    io.write"\t\t}\n\n"

    io.write"\t\t<R> R accept(Visitor<R> visitor) {\n"
    io.write("\t\t\treturn visitor.visit" .. className .. baseName .. "(this);\n")
    io.write"\t\t}\n"



    io.write"\t}\n\n\n"
end

local function defineVisitor(baseName, types)
    io.write"\tinterface Visitor<R> {\n"

    for typeName, fields in next,types,nil do
        local tn = string.trim(typeName)
        io.write("\t\tR visit" .. tn .. baseName .. "(" ..
          tn .. " " .. string.lower(baseName) .. ");\n")
    end

    io.write"\t}\n\n"
end

local function defineAst(outputPath, baseName, types)
    local path = outputPath .. baseName .. ".java"
    local file = io.open(path, "w")
    io.output(file)

    io.write
[[package emerald;

/*
 *
 * Autogenerated by Lua script
 * Script written by TheWaffleDimension
 *
 */


]]

    io.write"import java.util.List;\n\n"
    io.write("abstract class " .. baseName .. " {\n")

    defineVisitor(baseName, types)

    for className, fields in next,types,nil do
        defineType(baseName, className, fields)
    end

    io.write"\n\tabstract <R> R accept(Visitor<R> visitor);\n"

    io.write"}\n"
    io.close(file)
end

function main(argv)
    if #argv ~= 1 then
        print"Usage: generate_ast <output directory>"
    else
        local outputDir = argv[1]

        if outputDir:sub(-1) ~= "/" then outputDir = outputDir .. "/" end

        defineAst(
            outputDir,
            "Expr",
            {
                Assign = "Token name, Expr value",
                Binary = "Expr left, Token operator, Expr right",
                Grouping = "Expr expression",
                Literal = "Object value",
                Unary = "Token operator, Expr right",
                Variable = "Token name"
            }
        )

        defineAst(
            outputDir,
            "Stmt",
            {
                Block = "List<Stmt> statements",
                Expression = "Expr expression"
            }
        )
    end
end

main(arg)
